# Generated by Django 5.1 on 2024-08-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eshop_Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف بشود ؟')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساختن')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
