# Generated by Django 5.1 on 2024-08-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eshop_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام اسلایدر')),
                ('url', models.CharField(max_length=100, verbose_name='لبنک')),
                ('url_name', models.CharField(max_length=100, verbose_name='نام لبنک ')),
                ('img', models.ImageField(upload_to='images/sliders/', verbose_name='عکس مناسب')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
