# Generated by Django 5.1 on 2024-08-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_home', '0002_eshop_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshop_slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='eshop_slider',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
    ]
