# Generated by Django 5.1 on 2024-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category',
            name='url_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان لینک'),
        ),
    ]
