# Generated by Django 5.1 on 2024-08-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Blog', '0002_alter_blog_category_url_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='blog_category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshop_Blog.blog_category', verbose_name='دسته بندی'),
        ),
    ]
