# Generated by Django 5.1 on 2024-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Blog', '0003_alter_blog_category_options_blog_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='عنوان در لینک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('img', models.ImageField(upload_to='images/blog/', verbose_name='عکس مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('select_categories', models.ManyToManyField(to='Eshop_Blog.blog_category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
