# Generated by Django 5.1 on 2024-08-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Blog', '0005_blog_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
