# Generated by Django 5.1 on 2024-08-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Blog', '0008_alter_blog_author_alter_blog_category_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_delete', models.BooleanField(default=False, verbose_name='غیر فعال')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop_Blog.blog', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Eshop_Blog.blogcomment', verbose_name='زیر کامنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت ',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
