# Generated by Django 5.1 on 2024-08-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Blog', '0009_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
    ]
