# Generated by Django 5.1 on 2024-08-10 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='نام برند')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نام در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف کردن')),
                ('description', models.TextField(verbose_name='توضیحات برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف کردن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'unique_together': {('slug', 'id', 'is_active', 'is_delete')},
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف کردن')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
                'unique_together': {('slug', 'id', 'is_active', 'is_delete')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='نام')),
                ('price', models.FloatField(verbose_name='قیمت')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='ریت ها')),
                ('description', models.TextField(db_index=True, verbose_name='توضیحات اصلی')),
                ('short_description', models.TextField(db_index=True, verbose_name='توضیحات کوتاه')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف کردن')),
                ('category', models.ManyToManyField(db_index=True, related_name='Products', to='Eshop_Product.productcategory', verbose_name='کتگوری ها')),
                ('product_tags', models.ManyToManyField(related_name='Tags', to='Eshop_Product.producttag', verbose_name='تگ های محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'unique_together': {('slug', 'id', 'is_active', 'is_delete')},
            },
        ),
    ]
