# Generated by Django 5.1 on 2024-08-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='عنوان در url'),
        ),
    ]
