# Generated by Django 5.1 on 2024-08-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0002_alter_producttag_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('slug', 'id', 'is_active', 'is_delete')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('slug', 'id', 'is_active', 'is_delete')},
        ),
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together={('slug', 'id', 'is_active', 'is_delete')},
        ),
    ]
