# Generated by Django 5.1 on 2024-08-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshop_Product.productbrand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='Products', to='Eshop_Product.productcategory', verbose_name='کتگوری ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tags', to='Eshop_Product.producttag', verbose_name='تگ های محصول'),
        ),
    ]
