# Generated by Django 5.1 on 2024-08-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0003_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product/', verbose_name='تصویر محصول'),
        ),
    ]
