# Generated by Django 5.1 on 2024-08-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='Products', to='Eshop_Product.productcategory', verbose_name='کتگوری ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(related_name='Tags', to='Eshop_Product.producttag', verbose_name='تگ های محصول'),
        ),
    ]
