# Generated by Django 5.1 on 2024-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0005_alter_product_category_alter_product_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='Products', to='Eshop_Product.productcategory', verbose_name='کتگوری ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tags', to='Eshop_Product.producttag', verbose_name='تگ های محصول'),
        ),
    ]
