# Generated by Django 5.1 on 2024-08-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0007_productcategory_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
    ]
