# Generated by Django 5.1 on 2024-08-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0010_alter_productvisit_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/galleries', verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='Eshop_Product.product', verbose_name='گالری تصاویر')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالریها',
            },
        ),
    ]
