# Generated by Django 5.1 on 2024-08-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Product', '0011_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف کردن'),
        ),
    ]
