# Generated by Django 5.1 on 2024-08-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=50, verbose_name='ادرس سایت')),
                ('addr', models.CharField(max_length=50, verbose_name='ادرس')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تلفن')),
                ('phone_s', models.CharField(max_length=50, verbose_name='شماره تلفن ثابت')),
                ('email', models.CharField(max_length=50, verbose_name='ایمیل سایت ')),
                ('copyright', models.TextField(verbose_name='متن کپی رایت')),
                ('site_logo', models.ImageField(upload_to='images/site_setting_logo/', verbose_name='لوگو')),
                ('about_us', models.TextField(verbose_name='درباره ما')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حدف کردن')),
                ('is_main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی بودن')),
            ],
        ),
    ]
