# Generated by Django 5.1 on 2024-08-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_Setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظمات سایت', 'verbose_name_plural': 'تنظمات سایت'},
        ),
    ]
